title: TeatrAr
author: hdlabconicet
  name: hdlabconicet
  email: hdlabconicet@gmail.com
description: >
  Base de datos de obras teatrales escritas y representadas en Argentina entre el siglo XVIII y principios del siglo XX
baseurl: "/teatrar" # the subpath of your site, e.g. /blog
url: "https://hdlab.space" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: "jekyll/minima@1e8a445"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

minima:
  skin: classic
  nav_pages:
    - about.md
    - index.md
  social_links:
    - title: Repositorios en Github
      icon: github
      url: "https://github.com/hdlabconicet"
  hide_site_feed_link: true

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  obras:
    output: true
